### ISSUE TITLE
Refactor synapse-adjacent functions to use new reticulate-based synapser

### ISSUE THREAD

**Issue by allaway** [nf-osi/nfportalutils#94]
We should drop the custom import of the synapse python client in lieu of the new reticulate-based synapser, which likely will have better ongoing support (at least compared to us maintaining a custom import of the client) and will make it easier for users of this package to import in additional synapser functions/R docs instead of having to use synapseclient via reticulate.

**Comment by allaway** [comment]
e.g. currently someone using `nfportalutils` has to use `foo <- synapse$Synapse$tableQuery(.syn, "select * from syn12345")$asDataFrame()` to query a table, instead of just `foo <- synTableQuery("select * from syn12345")$asDataFrame()`

**Comment by allaway** [comment]
Well, I think I discovered at least one reason to do this: #164

**Comment by anngvu** [comment]
Using this to keep track: Function list to check for needed conversion to `synapser`, meaning that we use `synapser::synLogin()` and can run that function without issues. Some functions that don't need touching, e.g. they just do things like make diagrams, can be checked off with `NA`. 

- [x] .delim_string_to_vector - NA
- [ ] add_activity
- [ ] add_activity_batch
- [ ] add_default_fileview
- [ ] add_default_folders
- [ ] add_default_wiki
- [x] add_people_from_table - https://github.com/nf-osi/nfportalutils/pull/168
- [ ] add_publication_from_pubmed - #171
- [ ] add_publication_from_unpaywall - #171
- [ ] add_publications_from_file
- [ ] add_to_collection - #171
- [ ] add_to_scope
- [ ] adjust_view
- [ ] annotate_aligned_reads
- [ ] annotate_called_variants
- [ ] annotate_cnv
- [ ] annotate_expression
- [ ] annotate_with_manifest - #171
- [ ] annotate_with_tool_stats
- [ ] as_table_schema
- [ ] assign_study_data_types - #171
- [ ] bad_url
- [x] bipartite_mmd_template - NA
- [ ] byte_budget
- [ ] calculate_related_studies
- [ ] cbp_add_clinical
- [ ] cbp_add_cna
- [ ] cbp_add_expression
- [ ] cbp_add_maf
- [ ] cbp_new_cancer_type
- [ ] cbp_new_study
- [ ] check_access -  #171
- [ ] check_readpair_validity
- [ ] check_wiki_links
- [ ] convert_to_stringlist
- [ ] copy_annotations - #171
- [ ] data_curator_app_subpage
- [ ] delete_provenance
- [x] dsp_dataset_mapping - NA
- [ ] find_child - #171
- [ ] find_child_type - #171
- [ ] find_data_root - #171
- [ ] find_in - #171
- [ ] find_nf_asset - #171
- [ ] from_pubmed
- [ ] get_by_prop_from_json_schema
- [ ] get_dependency_from_json_schema
- [ ] get_project_wiki
- [ ] get_valid_values_from_json_schema
- [ ] grant_specific_file_access - #171
- [ ] infer_data_type - #171
- [x] key_label_to_id - NA
- [ ] list_project_datasets
- [ ] make_admin
- [ ] make_folder
- [ ] make_public
- [ ] make_public_viewable
- [ ] manifest_generate - #171
- [x] manifest_passed - NA
- [x] manifest_validate - NA
- [ ] map_sample_input_ss
- [ ] map_sample_io
- [ ] map_sample_output_rnaseq
- [ ] map_sample_output_sarek
- [ ] meta_qc_dataset  - #171
- [ ] meta_qc_project  - #171
- [ ] missing_annotation_email
- [ ] new_dataset - #171
- [ ] new_project
- [ ] nf_cnv_dataset
- [ ] nf_sarek_datasets
- [ ] nf_star_salmon_datasets
- [ ] nf_workflow_version
- [x] precheck_manifest - NA
- [ ] processing_flowchart
- [ ] register_study
- [ ] register_study_files
- [ ] remanifest
- [ ] remove_button
- [ ] remove_wiki_subpage
- [ ] summarize_attribute
- [ ] summarize_file_access - #171
- [ ] swap_col
- [ ] syn_login
- [ ] table_query
- [ ] update_study_annotations
- [ ] use_latest_in_collection - #171
- [ ] wiki_mod
